style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/momotaro98/qiic
options:
  commits:
    filters:
      Type:
        - sparkles
        - bug
    #     - racehorse
    #     - recycle
  commit_groups:
    title_maps:
      sparkles: Features
      bug: Bug Fixes
    #   racehorse: Performance Improvements
    #   recycle: Code Refactoring
  header:
    pattern: "^:(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
