on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.1

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Test
      run: make test

  release:
    strategy:
      matrix:
        go-version: 1.13.1
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build
      run: make build
